name: Build Linux musl artifact

on:
  push:
    branches: [build_fix]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-musl:
    name: Build x86_64-unknown-linux-musl
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          key: x86_64-unknown-linux-musl

      # Build using the "Build Rust projects with cross" action
      - name: Build with cross (musl)
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: x86_64-unknown-linux-musl
          args: --locked --release
          strip: true

      - name: Prepare binary
        shell: bash
        run: |
          set -euo pipefail
          BIN_NAME="iroh-ssh"
          TARGET="x86_64-unknown-linux-musl"
          SRC="target/${TARGET}/release/${BIN_NAME}"
          OUTDIR="dist/${TARGET}"
          mkdir -p "${OUTDIR}"
          if [ ! -f "${SRC}" ]; then
            echo "Built binary not found: ${SRC}"
            exit 1
          fi

          # Optionally rename for clarity
          cp "${SRC}" "${OUTDIR}/${BIN_NAME}"
          chmod +x "${OUTDIR}/${BIN_NAME}"
          echo "Resulting files:"
          ls -la "${OUTDIR}"

          # Print dynamic deps (should be mostly static if fully musl)
          echo "ldd output (expected 'not a dynamic executable' for fully static):"
          ldd "${OUTDIR}/${BIN_NAME}" || true

      - name: Upload musl binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: iroh-ssh-x86_64-unknown-linux-musl
          path: dist/x86_64-unknown-linux-musl/*
          retention-days: 2