name: Build cross-platform artifacts

on:
  push:
    branches: [build_win]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Linux x86_64 (musl)
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl
            ext: ""
          - name: Windows x86_64 (MSVC)
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
          - name: macOS x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.target }}

      - name: Build with cross
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: --locked --release
          strip: true

      - name: Prepare binary
        shell: bash
        run: |
          set -euo pipefail
          BIN_NAME="iroh-ssh"
          TARGET="${{ matrix.platform.target }}"
          EXT="${{ matrix.platform.ext }}"
          
          
          # Determine output extension: keep .exe on Windows, add .linux or .macos for others
          OUT_EXT="${EXT}"
          if [ -z "${OUT_EXT}" ]; then
            if [[ "${TARGET}" == *"linux"* ]]; then
              OUT_EXT=".linux"
            elif [[ "${TARGET}" == *"apple-darwin"* ]]; then
              OUT_EXT=".macos"
            else
              OUT_EXT=""
            fi
          fi

          SRC="target/${TARGET}/release/${BIN_NAME}${EXT}"
          OUTDIR="dist/${TARGET}"
          mkdir -p "${OUTDIR}"
          if [ ! -f "${SRC}" ]; then
            echo "Built binary not found: ${SRC}"
            exit 1
          fi
          cp "${SRC}" "${OUTDIR}/${BIN_NAME}${OUT_EXT}"
          chmod +x "${OUTDIR}/${BIN_NAME}${OUT_EXT}" || true
          echo "Resulting files:"
          ls -la "${OUTDIR}"

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: iroh-ssh-${{ matrix.platform.target }}
          path: dist/${{ matrix.platform.target }}/*
          retention-days: 2